[phases.setup]
# desativa rollup nativo, que quebra o build
env.ROLLUP_SKIP_NODE_NATIVE = "true"

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run preview"
